name: env-file-maven-plugin Lint and Test
on:
  push: 
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Lint Project Files
        uses: ./.github/actions/lint
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'corretto' ]
        java: [ '8' ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3        
            
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'maven' 

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Maven Test via Package
        id: run_maven_test_via_package
        run: |
          mvn clean package